version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    deploy:
      resources:
        limits:
          memory: 512M # Adjust as needed

  redis:
    build:
      context: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          memory: 512M # Adjust memory for Redis as needed

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # If you need HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redis
      - rabbitmq
    deploy:
      resources:
        limits:
          memory: 256M # Adjust as needed

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./redis-data